GET http://localhost:8062/api/v1/listings

###

GET http://localhost:8062/api/v1/listings/15


###

POST http://localhost:8062/api/v1/listings
Content-Type: application/json 

{
    "title" : "Llama",
    "description" : "alpaca",
    "pay" : 100,
    "duration" : 45,
    "creator" : "Creator1"
}

###
DELETE http://localhost:3000/listings/6698258a2513d0bb31d43793


###
PATCH http://localhost:3000/listings/6698260d26ea99563d1be4be
Content-Type: application/json

{
    "title" : "new title",
    "description" : "New description"
}


### Users ///////////////////////////////////////////
GET http://localhost:8062/api/v1/users

###
GET http://localhost:8062/api/v1/users/66ac21268f7019593fe0ad2f

###
POST http://localhost:8062/api/v1/users
Content-Type: application/json 

{
    "profilePicture" : "https://www.hollywoodreporter.com/wp-content/uploads/2022/04/12fea_mads_splash-2022.jpg?w=2000&h=1126&crop=1",
    "userID" : "Madds",
    "jobsAppliedTo" : [],
    "jobsCreated" : [],
    "reviews" : [],
    "money" : 3000
}

###
DELETE http://localhost:3000/api/v1/users/66aa86c48a1ee6b043d6e3cf

###
PATCH http://localhost:3000/api/v1/users/6698260d26ea99563d1be4be
Content-Type: application/json

{
    "title" : "new title",
    "description" : "New description"
}