GET http://localhost:8062/api/v1/listings

###

GET http://localhost:3000/api/v1/listings/15


###

POST http://localhost:8062/listings
Content-Type: application/json 

{
    "title" : "Job1",
    "description" : "desc",
    "pay" : 100,
    "duration" : 45,
    "creator" : "Creator1"
}

###
DELETE http://localhost:3000/listings/6698258a2513d0bb31d43793


###
PATCH http://localhost:3000/listings/6698260d26ea99563d1be4be
Content-Type: application/json

{
    "title" : "new title",
    "description" : "New description"
}


### Users
GET http://localhost:8062/api/v1/users

###
GET http://localhost:8062/api/v1/users/66aa86c48a1ee6b043d6e3cf

###
POST http://localhost:8062/api/v1/users
Content-Type: application/json 

{
    "profilePicture" : "https://www.korosenai.es/wp-content/uploads/2021/01/ganyu-genshin-impact.jpg",
    "userID" : "Ganyu",
    "jobsAppliedTo" : [],
    "jobsCreated" : [],
    "reviews" : [],
    "money" : 1200,
}

###
DELETE http://localhost:3000/api/v1/users/66aa86c48a1ee6b043d6e3cf

###
PATCH http://localhost:3000/api/v1/users/6698260d26ea99563d1be4be
Content-Type: application/json

{
    "title" : "new title",
    "description" : "New description"
}